# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f0ddf0c934f039420fcf4596c3bda3559a098d6e11aa05b1ca1010d508a1662ec1a729e762b9bc9ea8859a340b7ae999be08bd7b4367137d468fe18b8488040

test:
  secret_key_base: 23f1d3f0155cda9548a7f21c1e10e48be5740b363ad1377d3ee57b604a1213183ff464ce47c41df0773ecfe2a43f42b392366a7bbd9e7b86c0523c9139e5d500

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
